[package]
name = "type_solver"
authors.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
interner.workspace = true
symbols.workspace = true
ast.workspace = true
ir_builder.workspace = true
gxhash = "3.4.1"
