[package]
name = "import_resolver"
authors.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
interner.workspace = true
symbols.workspace = true
ast.workspace = true
lexer.workspace = true
parser.workspace = true
gxhash = "3.4.1"
