name: Cargo Bloat Check

on:
  pull_request:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo_bloat:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: rui314/setup-mold@v1
    - run: rustup toolchain install stable --profile minimal
    - name: Run rust cache
      uses: Swatinem/rust-cache@v2
      with:
        cache-all-crates: "true"
    - name: Run cargo bloat
      uses: orf/cargo-bloat-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
